### ISSUE TITLE
Program freeze after NumberFormatException 

### ISSUE THREAD

**Issue by Fabus1184** [stpe/jniosemu#7]
NumberFormatExceptions are thrown sometimes when immediate values or variable initializers are too big to be stored. This makes all buttons have no effect when clicked and not being able to save or exit the program.

I am running Linux with OpenJDK version 1.8.0_322.

Steps to reproduce:
assemble the following program
```asm
.data
	a: .byte 0xFFFFFFFFFFFFFFFF
.end
```

This will result in the following exception:

```
Exception in thread "Thread-0" java.lang.NumberFormatException: For input string: "FFFFFFFFFFFFFFFF"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:592)
	at jniosemu.emulator.compiler.Compiler.parseValue(Compiler.java:165)
	at jniosemu.emulator.compiler.Compiler.parseValue(Compiler.java:93)
	at jniosemu.emulator.compiler.Variable.<init>(Variable.java:37)
	at jniosemu.emulator.compiler.Compiler.parseLine(Compiler.java:323)
	at jniosemu.emulator.compiler.Compiler.parseLine(Compiler.java:278)
	at jniosemu.emulator.compiler.Compiler.compile(Compiler.java:448)
	at jniosemu.emulator.EmulatorManager.compile(EmulatorManager.java:306)
	at jniosemu.emulator.EmulatorManager.update(EmulatorManager.java:413)
	at jniosemu.events.EventManager$EventSender.sendEvent(EventManager.java:294)
	at jniosemu.events.EventManager$EventSender.run(EventManager.java:254)
```

**Comment by bircni** [comment]
This also happens on Windows 10 & 11

**Comment by Fabus1184** [comment]
Yes 😄
